In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv(r"C:\Users\divya\Downloads\emp_sal.csv")

In [2]:
dataset

Position  Level   Salary
0  Jr Software Engineer      1    45000
1  Sr Software Engineer      2    50000
2             Team Lead      3    60000
3               Manager      4    80000
4            Sr manager      5   110000
5        Region Manager      6   150000
6                   AVP      7   200000
7                    VP      8   300000
8                   CTO      9   500000
9                   CEO     10  1000000

In [3]:
X=dataset.iloc[:,1:2].values
y=dataset.iloc[:,2].values

In [4]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

# Decision Tree ML regression model

In [7]:
from sklearn.tree import DecisionTreeRegressor
dt_model=DecisionTreeRegressor()
dt_model.fit(X,y)

dt_model_pred=dt_model.predict([[6.5]])
dt_model_pred

array([150000.])

# Random Forest Regression Model 

In [14]:
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor(random_state=0)
rf_model.fit(X,y)

rf_model_pred=rf_model.predict([[6.5]])
rf_model_pred

array([158300.])