# 1 MAY

In [1]:
import numpy as np

In [4]:

b=np.random.randint(10,20,(5,4))

In [5]:
b[:]


array([[16, 15, 12, 13],
       [10, 15, 10, 14],
       [17, 18, 15, 17],
       [10, 13, 14, 17],
       [13, 16, 13, 17]])

In [6]:
b[1:3]

array([[10, 15, 10, 14],
       [17, 18, 15, 17]])

In [7]:
b[1,2]

10

In [8]:
b[1,-1]

14

In [9]:
b[2:3]

array([[17, 18, 15, 17]])

In [10]:
b[0:-2]

array([[16, 15, 12, 13],
       [10, 15, 10, 14],
       [17, 18, 15, 17]])

In [11]:
arr2=np.random.randint(0,100,(10,10))

In [12]:
arr2

array([[32, 92, 87, 43, 26, 91, 17, 55, 80, 91],
       [ 6,  6, 79, 47, 58, 12, 67, 53, 29, 38],
       [77, 52,  5, 15, 30, 87, 13, 52, 11, 13],
       [12, 36, 30, 39,  1, 57, 61, 54, 10, 93],
       [28, 72,  3, 34, 84, 59, 89, 88, 14, 66],
       [54, 25, 85, 50, 71, 80, 33, 87, 37, 79],
       [65, 95, 71,  3, 20,  2, 27, 96,  4, 63],
       [22, 67, 81, 51, 18, 93, 52,  7, 83, 71],
       [49, 26, 74, 96, 73, 39, 78, 73, 59, 49],
       [92, 35, 14, 33,  0, 44, 16, 24,  4, 34]])

In [13]:
arr2[::-1]

array([[92, 35, 14, 33,  0, 44, 16, 24,  4, 34],
       [49, 26, 74, 96, 73, 39, 78, 73, 59, 49],
       [22, 67, 81, 51, 18, 93, 52,  7, 83, 71],
       [65, 95, 71,  3, 20,  2, 27, 96,  4, 63],
       [54, 25, 85, 50, 71, 80, 33, 87, 37, 79],
       [28, 72,  3, 34, 84, 59, 89, 88, 14, 66],
       [12, 36, 30, 39,  1, 57, 61, 54, 10, 93],
       [77, 52,  5, 15, 30, 87, 13, 52, 11, 13],
       [ 6,  6, 79, 47, 58, 12, 67, 53, 29, 38],
       [32, 92, 87, 43, 26, 91, 17, 55, 80, 91]])

In [14]:
arr2[:-3]

array([[32, 92, 87, 43, 26, 91, 17, 55, 80, 91],
       [ 6,  6, 79, 47, 58, 12, 67, 53, 29, 38],
       [77, 52,  5, 15, 30, 87, 13, 52, 11, 13],
       [12, 36, 30, 39,  1, 57, 61, 54, 10, 93],
       [28, 72,  3, 34, 84, 59, 89, 88, 14, 66],
       [54, 25, 85, 50, 71, 80, 33, 87, 37, 79],
       [65, 95, 71,  3, 20,  2, 27, 96,  4, 63]])

In [15]:
arr=np.arange(10,30,5)


# Operation

In [18]:
arr.reshape(2,2)

array([[10, 15],
       [20, 25]])

In [17]:
arr

array([10, 15, 20, 25])

In [19]:
arr.reshape(2,2,order='F')

array([[10, 20],
       [15, 25]])

In [20]:
arr.reshape(2,2,order='C')

array([[10, 15],
       [20, 25]])

In [21]:
arr.reshape(2,2,order='A')

array([[10, 15],
       [20, 25]])

# Indexing

In [22]:
mat=np.arange(0,100).reshape(10,10)

In [23]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
mat[4,5]

45

In [26]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [29]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [28]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [30]:
mat[1:2,2:4]

array([[12, 13]])

In [32]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# Masking

In [33]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
id(mat)

2736339003952

In [35]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
mat[mat==50]

array([50])

In [39]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])