# 30 April


# NumPY

In [1]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating LIST

In [6]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

# below code we are converting list to array

In [8]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
type(my_list)

list

In [ ]:
np. # lear about multiple function

In [ ]:
# ARANGE

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,20)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [21]:
np.arange(10,10)

array([], dtype=int32)

In [22]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [23]:
#ZEROS


In [33]:
np.zeros(10) # Parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros(5,dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [27]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [28]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [29]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [35]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
# ones


In [37]:
np.ones(3)

array([1., 1., 1.])

In [38]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [40]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
rand(3,2)

NameError: name 'rand' is not defined

In [42]:
random.rand(3,2)

NameError: name 'random' is not defined

In [46]:
np.random.rand(5)

array([0.58351541, 0.00204912, 0.57363767, 0.67850331, 0.03076584])

In [47]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [48]:
np.random.rand(3,5)

array([[0.86514336, 0.97820956, 0.65612424, 0.15067918, 0.98871392],
       [0.17456201, 0.55933936, 0.50632371, 0.7514394 , 0.51600436],
       [0.6682998 , 0.38944438, 0.4998667 , 0.88305846, 0.72651053]])

In [56]:
np.random.randint(4,6)

5

In [66]:
np.random.randint(10,20,6)

array([11, 19, 15, 17, 13, 14])

In [60]:
np.random.randint(0,1)

0

In [69]:
np.random.randint(10,40,(10,10))

array([[12, 31, 26, 11, 19, 25, 28, 11, 15, 34],
       [15, 29, 35, 32, 39, 10, 26, 37, 10, 17],
       [29, 15, 11, 21, 13, 16, 37, 36, 19, 12],
       [16, 25, 20, 30, 29, 23, 16, 26, 18, 34],
       [10, 29, 25, 15, 38, 24, 26, 20, 35, 34],
       [24, 10, 30, 17, 18, 37, 30, 29, 38, 30],
       [32, 24, 38, 33, 25, 10, 34, 19, 16, 25],
       [20, 27, 37, 20, 23, 36, 10, 35, 10, 18],
       [18, 31, 27, 14, 14, 20, 33, 21, 19, 14],
       [22, 22, 35, 21, 29, 10, 30, 30, 21, 33]])

In [70]:
#ARANGE

In [71]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
np.arange(1,13).reshape(3,6) # x*y should be equal to len of array

ValueError: cannot reshape array of size 12 into shape (3,6)

# SLICING IN MATRIX

In [78]:
b=np.random.randint(10,20,(5,4))

In [79]:
b

array([[17, 11, 18, 11],
       [15, 15, 15, 15],
       [10, 18, 17, 12],
       [16, 17, 13, 14],
       [17, 11, 17, 19]])

In [80]:
b[:]

array([[17, 11, 18, 11],
       [15, 15, 15, 15],
       [10, 18, 17, 12],
       [16, 17, 13, 14],
       [17, 11, 17, 19]])